### ISSUE TITLE
前两天更新以后就加载不了了，救救孩子

### ISSUE THREAD

**Issue by 2085673514** [qwerdvd/StarRailUID#31] opened 2023-05-16 10:27 UTC
控制台报错是这个
05-16 18:21:06 [INFO] gsuid_core.sv | 载入regex触发器【\d+】!
  File "C:\NoneBot2\gsuid_core\gsuid_core\server.py", line 50, in load_plugins
    self.load_dir_plugins(path, True)
  File "C:\NoneBot2\gsuid_core\gsuid_core\server.py", line 77, in load_dir_plugins
    importlib.import_module(f'{_p}.__init__')
  File "C:\users\20856\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\NoneBot2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 11, in <module>
    from .to_card import api_to_card
  File "C:\NoneBot2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_card.py", line 8, in <module>
    from .to_data import api_to_dict
  File "C:\NoneBot2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_data.py", line 4, in <module>
    from mpmath import mp
None
  File "C:\NoneBot2\gsuid_core\gsuid_core\server.py", line 50, in load_plugins
    self.load_dir_plugins(path, True)
  File "C:\NoneBot2\gsuid_core\gsuid_core\server.py", line 77, in load_dir_plugins
    importlib.import_module(f'{_p}.__init__')
  File "C:\users\20856\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\NoneBot2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 11, in <module>
    from .to_card import api_to_card
  File "C:\NoneBot2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_card.py", line 8, in <module>
    from .to_data import api_to_dict
  File "C:\NoneBot2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\to_data.py", line 4, in <module>
    from mpmath import mp
05-16 18:21:06 [WARNING] gsuid_core.server | 插件StarRailUID加载失败

**Comment by qwerdvd** [comment] 2023-05-16 10:32
Duplicate of #11 #21

**Comment by qwerdvd** [comment] 2023-05-16 10:32
请按照这几个issue的方式安装依赖

**Comment by 2085673514** [comment] 2023-05-16 10:40
ok，谢谢大佬

**Closed** 2023-05-16 10:42 UTC
